package main

import (
	"fmt"
	"io"
	"strings"
)

const referenceFile = "docs/manage-help.txt"

func writeReference(w io.Writer) {
	fmt.Fprintf(w, "%s command reference\n\nGenerated by `go run ./cmd/%s docs > %s`.\nA test byte-diffs this file against the binary; regenerate it, never edit it.\n",
		toolName, toolName, referenceFile)
	section(w, "--help", rootPage())
	grouped := map[string]bool{}
	for _, v := range verbs {
		if group, _, ok := strings.Cut(v.name, " "); ok && !grouped[group] {
			grouped[group] = true
			section(w, group+" --help", groupPage(group))
		}
		section(w, v.name+" --help", verbPage(v))
	}
}

func section(w io.Writer, args, page string) {
	fmt.Fprintf(w, "\n==> %s %s\n\n%s", toolName, args, page)
}

func runDocs(e *env, v *verb, args []string) error {
	if _, err := parseVerb(e, v, args); err != nil {
		return err
	}
	writeReference(e.stdout)
	return nil
}
